# Generated by Django 6.0 on 2026-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.URLField(max_length=700)),
                ('summary', models.TextField(max_length=700)),
            ],
        ),
    ]
