# Generated by Django 6.0 on 2026-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.TextField(default='Goutam Kumar', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(max_length=700),
        ),
    ]
