# Generated by Django 6.0 on 2026-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0002_course_instructor_name_alter_course_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.TextField(max_length=20),
        ),
    ]
