# Generated by Django 6.0 on 2026-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0004_alter_course_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(),
        ),
    ]
