# Generated by Django 6.0 on 2026-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0005_alter_course_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(default='This course introduces fundamental concepts of computer systems and information technology. It covers basic hardware and software components, operating systems, data management, and essential computer applications. Students develop practical skills in using computers effectively, understanding digital tools, and applying problem-solving techniques relevant to academic and professional environments. ', max_length=5000),
        ),
    ]
